if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'AGE'
'BALANCE'
'COUNTRY'
'CREDITSCORE'
'ESTIMATEDSALARY'
'GENDER'
'HASCREDITCARD'
'ISACTIVEMEMBER'
'NUMOFPRODUCTS'
'TENURE'
) then ROLE='INPUT';
else delete;
end;
